baseURL = 'https://ohdeerneil.github.io/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'beautifulhugo'
copyright = "©️ 2021 - 2025 | Neil De Hert"

[params]
  description = "Enthousiastic Game Programmer"

[Params.author]
    name = "Neil De Hert"
    website = "https://ohdeerneil.github.io"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Me"
    url = "/about-me"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 3