baseURL = 'https://ohdeerneil.github.io/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'beautifulhugo'


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Me"
    url = "/about-me"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 3